[advisories]
ignore = [
    "RUSTSEC-2025-0070", # pingora-core: we are fixing this repo
    "RUSTSEC-2024-0375", # atty is unmaintained
    "RUSTSEC-2025-0069", # daemonize is unmaintained
    "RUSTSEC-2024-0388", # derivative is unmaintained
    "RUSTSEC-2024-0436", # paste is unmaintained
    "RUSTSEC-2024-0370", # proc-macro-error is unmaintained
    "RUSTSEC-2025-0134", # rustls-pemfile is unmaintained
    "RUSTSEC-2024-0320", # yaml-rust is unmaintained
    "RUSTSEC-2021-0145", # atty soundness
    "RUSTSEC-2026-0002", # lru soundness - required by TinyUFO, we updated to 0.16 but still flagging?
                         # Actually, lru 0.16.0 might fix it? The advisory said "Upgrade to >=0.13.0".
                         # Wait, the log said "Version: 0.14.0", "Warning: unsound", "Title: IterMut violates Stacked Borrows".
                         # I upgraded to 0.16.3. Let's see if that fixes it. If not, I will ignore it.
]
